version: '3.7'
services:
    registry:
        image: registry:2.8.1
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.registry.rule=Host(`registry.region-operator.ru`)
                - traefik.http.services.registry.loadBalancer.server.port=5000
                - traefik.http.routers.registry.middlewares=secure-headers
                - traefik.http.routers.registry.entryPoints=https
                - traefik.http.routers.registry.tls=true
                - traefik.http.routers.registry.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 1s
        networks:
            - traefik-public
        volumes:
            - registry:/var/lib/registry

volumes:
    registry:

networks:
    traefik-public:
        external: true
